# Generated by Django 5.2.8 on 2026-07-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahberapp', '0003_manualpayment_ethiopian_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpayment',
            name='ethiopian_month',
        ),
        migrations.RemoveField(
            model_name='manualpayment',
            name='ethiopian_year',
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payments', to='mahberapp.meeting'),
        ),
    ]
