# Generated by Django 5.2.8 on 2026-07-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahberapp', '0004_remove_manualpayment_ethiopian_month_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['meeting'], name='mahberapp_a_meeting_81ac5c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member'], name='mahberapp_a_member__33d4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['meeting', 'is_paid'], name='mahberapp_c_meeting_6ba541_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member'], name='mahberapp_c_member__a79170_idx'),
        ),
        migrations.AddIndex(
            model_name='manualpayment',
            index=models.Index(fields=['meeting'], name='mahberapp_m_meeting_894165_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['ethiopian_year'], name='mahberapp_m_ethiopi_3a44e6_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['ethiopian_month', 'ethiopian_year'], name='mahberapp_m_ethiopi_c77dff_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['member'], name='mahberapp_p_member__29ad47_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['meeting', 'is_paid'], name='mahberapp_p_meeting_091d0d_idx'),
        ),
    ]
